export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL';
export const CREATE_ORDER_RESET = 'CREATE_ORDER_RESET';

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL';
export const ORDER_DETAILS_RESET = 'ORDER_DETAILS_RESET';

export const ORDER_SIMILAR_PRODUCT_REQUEST = 'ORDER_SIMILAR_PRODUCT_REQUEST';
export const ORDER_SIMILAR_PRODUCT_SUCCESS = 'ORDER_SIMILAR_PRODUCT_SUCCESS';
export const ORDER_SIMILAR_PRODUCT_FAIL = 'ORDER_SIMILAR_PRODUCT_FAIL';
export const ORDER_SIMILAR_PRODUCT_RESET = 'ORDER_SIMILAR_PRODUCT_RESET';

export const GET_MY_ORDERS_REQUEST = 'GET_MY_ORDERS_REQUEST';
export const GET_MY_ORDERS_SUCCESS = 'GET_MY_ORDERS_SUCCESS';
export const GET_MY_ORDERS_FAIL = 'GET_MY_ORDERS_FAIL';
export const GET_MY_ORDERS_RESET = 'GET_MY_ORDERS_RESET';
