export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL';

export const GET_LATEST_PRODUCTS_REQUEST = 'GET_LATEST_PRODUCTS_REQUEST';
export const GET_LATEST_PRODUCTS_SUCCESS = 'GET_LATEST_PRODUCTS_SUCCESS';
export const GET_LATEST_PRODUCTS_FAIL = 'GET_LATEST_PRODUCTS_FAIL';

export const GET_MOST_RATED_PRODUCTS_REQUEST =
   'GET_MOST_RATED_PRODUCTS_REQUEST';
export const GET_MOST_RATED_PRODUCTS_SUCCESS =
   'GET_MOST_RATED_PRODUCTS_SUCCESS';
export const GET_MOST_RATED_PRODUCTS_FAIL = 'GET_MOST_RATED_PRODUCTS_FAIL';

export const GET_SINGLE_PRODUCT_REQUEST = 'GET_SINGLE_PRODUCT_REQUEST';
export const GET_SINGLE_PRODUCT_SUCCESS = 'GET_SINGLE_PRODUCT_SUCCESS';
export const GET_SINGLE_PRODUCT_FAIL = 'GET_SINGLE_PRODUCT_FAIL';

export const GET_PRODUCTS_FROM_BRAND_REQUEST =
   'GET_PRODUCTS_FROM_BRAND_REQUEST';
export const GET_PRODUCTS_FROM_BRAND_SUCCESS =
   'GET_PRODUCTS_FROM_BRAND_SUCCESS';
export const GET_PRODUCTS_FROM_BRAND_FAIL = 'GET_PRODUCTS_FROM_BRAND_FAIL';

export const GET_PRODUCTS_FROM_CATEGORY_REQUEST =
   'GET_PRODUCTS_FROM_CATEGORY_REQUEST';
export const GET_PRODUCTS_FROM_CATEGORY_SUCCESS =
   'GET_PRODUCTS_FROM_CATEGORY_SUCCESS';
export const GET_PRODUCTS_FROM_CATEGORY_FAIL =
   'GET_PRODUCTS_FROM_CATEGORY_FAIL';

export const CREATE_PRODUCT_REVIEW_REQUEST = 'CREATE_PRODUCT_REVIEW_REQUEST';
export const CREATE_PRODUCT_REVIEW_SUCCESS = 'CREATE_PRODUCT_REVIEW_SUCCESS';
export const CREATE_PRODUCT_REVIEW_FAIL = 'CREATE_PRODUCT_REVIEW_FAIL';
export const CREATE_PRODUCT_REVIEW_RESET = 'CREATE_PRODUCT_REVIEW_RESET';
