export const GET_ADMIN_ORDERS_REQUEST = 'GET_ADMIN_ORDERS_REQUEST';
export const GET_ADMIN_ORDERS_SUCCESS = 'GET_ADMIN_ORDERS_SUCCESS';
export const GET_ADMIN_ORDERS_FAIL = 'GET_ADMIN_ORDERS_FAIL';
export const GET_ADMIN_ORDERS_RESET = 'GET_ADMIN_ORDERS_RESET';

export const ADMIN_ORDER_DETAILS_REQUEST = 'ADMIN_ORDER_DETAILS_REQUEST';
export const ADMIN_ORDER_DETAILS_SUCCESS = 'ADMIN_ORDER_DETAILS_SUCCESS';
export const ADMIN_ORDER_DETAILS_FAIL = 'ADMIN_ORDER_DETAILS_FAIL';
export const ADMIN_ORDER_DETAILS_RESET = 'ADMIN_ORDER_DETAILS_RESET';

export const ADMIN_PAY_ORDER_REQUEST = 'ADMIN_PAY_ORDER_REQUEST';
export const ADMIN_PAY_ORDER_SUCCESS = 'ADMIN_PAY_ORDER_SUCCESS';
export const ADMIN_PAY_ORDER_FAIL = 'ADMIN_PAY_ORDER_FAIL';
export const ADMIN_PAY_ORDER_RESET = 'ADMIN_PAY_ORDER_RESET';

export const ADMIN_DELIVER_ORDER_REQUEST = 'ADMIN_DELIVER_ORDER_REQUEST';
export const ADMIN_DELIVER_ORDER_SUCCESS = 'ADMIN_DELIVER_ORDER_SUCCESS';
export const ADMIN_DELIVER_ORDER_FAIL = 'ADMIN_DELIVER_ORDER_FAIL';
export const ADMIN_DELIVER_ORDER_RESET = 'ADMIN_DELIVER_ORDER_RESET';
