export const GET_SELLER_PRODUCTS_REQUEST = 'GET_SELLER_PRODUCTS_REQUEST';
export const GET_SELLER_PRODUCTS_SUCCESS = 'GET_SELLER_PRODUCTS_SUCCESS';
export const GET_SELLER_PRODUCTS_FAIL = 'GET_SELLER_PRODUCTS_FAIL';

export const GET_ADMIN_PRODUCTS_REQUEST = 'GET_ADMIN_PRODUCTS_REQUEST';
export const GET_ADMIN_PRODUCTS_SUCCESS = 'GET_ADMIN_PRODUCTS_SUCCESS';
export const GET_ADMIN_PRODUCTS_FAIL = 'GET_ADMIN_PRODUCTS_FAIL';

export const SELLER_CREATE_PRODUCT_REQUEST = 'SELLER_CREATE_PRODUCT_REQUEST';
export const SELLER_CREATE_PRODUCT_SUCCESS = 'SELLER_CREATE_PRODUCT_SUCCESS';
export const SELLER_CREATE_PRODUCT_FAIL = 'SELLER_CREATE_PRODUCT_FAIL';
export const SELLER_CREATE_PRODUCT_RESET = 'SELLER_CREATE_PRODUCT_RESET';

export const SELLER_UPDATE_PRODUCT_REQUEST = 'SELLER_UPDATE_PRODUCT_REQUEST';
export const SELLER_UPDATE_PRODUCT_SUCCESS = 'SELLER_UPDATE_PRODUCT_SUCCESS';
export const SELLER_UPDATE_PRODUCT_FAIL = 'SELLER_UPDATE_PRODUCT_FAIL';
export const SELLER_UPDATE_PRODUCT_RESET = 'SELLER_UPDATE_PRODUCT_RESET';

export const GET_SELLER_PRODUCT_REQUEST = 'GET_SELLER_PRODUCT_REQUEST';
export const GET_SELLER_PRODUCT_SUCCESS = 'GET_SELLER_PRODUCT_SUCCESS';
export const GET_SELLER_PRODUCT_FAIL = 'GET_SELLER_PRODUCT_FAIL';

export const GET_ADMIN_PRODUCT_REQUEST = 'GET_ADMIN_PRODUCT_REQUEST';
export const GET_ADMIN_PRODUCT_SUCCESS = 'GET_ADMIN_PRODUCT_SUCCESS';
export const GET_ADMIN_PRODUCT_FAIL = 'GET_ADMIN_PRODUCT_FAIL';

export const SELLER_DELETE_PRODUCT_REQUEST = 'SELLER_DELETE_PRODUCT_REQUEST';
export const SELLER_DELETE_PRODUCT_SUCCESS = 'SELLER_DELETE_PRODUCT_SUCCESS';
export const SELLER_DELETE_PRODUCT_FAIL = 'SELLER_DELETE_PRODUCT_FAIL';
export const SELLER_DELETE_PRODUCT_RESET = 'SELLER_DELETE_PRODUCT_RESET';
