export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';

export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';
export const UPDATE_USER_RESET = 'UPDATE_USER_RESET';

export const CHANGE_USER_LOGIN_REQUEST = 'CHANGE_USER_LOGIN_REQUEST';
export const CHANGE_USER_LOGIN_SUCCESS = 'CHANGE_USER_LOGIN_SUCCESS';
export const CHANGE_USER_LOGIN_FAIL = 'CHANGE_USER_LOGIN_FAIL';

export const USER_LOGOUT = 'USER_LOGOUT';
