export const REGISTER_SELLER_USER_REQUEST = 'REGISTER_SELLER_USER_REQUEST';
export const REGISTER_SELLER_USER_SUCCESS = 'REGISTER_SELLER_USER_SUCCESS';
export const REGISTER_SELLER_USER_FAIL = 'REGISTER_SELLER_USER_FAIL';

export const LOGIN_SELLER_USER_REQUEST = 'LOGIN_SELLER_USER_REQUEST';
export const LOGIN_SELLER_USER_SUCCESS = 'LOGIN_SELLER_USER_SUCCESS';
export const LOGIN_SELLER_USER_FAIL = 'LOGIN_SELLER_USER_FAIL';

export const UPDATE_SELLER_USER_REQUEST = 'UPDATE_SELLER_USER_REQUEST';
export const UPDATE_SELLER_USER_SUCCESS = 'UPDATE_SELLER_USER_SUCCESS';
export const UPDATE_SELLER_USER_FAIL = 'UPDATE_SELLER_USER_FAIL';
export const UPDATE_SELLER_USER_RESET = 'UPDATE_SELLER_USER_RESET';

export const CHANGE_SELLER_LOGIN_REQUEST = 'CHANGE_SELLER_LOGIN_REQUEST';
export const CHANGE_SELLER_LOGIN_SUCCESS = 'CHANGE_SELLER_LOGIN_SUCCESS';
export const CHANGE_SELLER_LOGIN_FAIL = 'CHANGE_SELLER_LOGIN_FAIL';

export const ADMIN_GET_USERS_REQUEST = 'ADMIN_GET_USERS_REQUEST';
export const ADMIN_GET_USERS_SUCCESS = 'ADMIN_GET_USERS_SUCCESS';
export const ADMIN_GET_USERS_FAIL = 'ADMIN_GET_USERS_FAIL';

export const ADMIN_GET_SELLERS_REQUEST = 'ADMIN_GET_SELLERS_REQUEST';
export const ADMIN_GET_SELLERS_SUCCESS = 'ADMIN_GET_SELLERS_SUCCESS';
export const ADMIN_GET_SELLERS_FAIL = 'ADMIN_GET_SELLERS_FAIL';

export const ADMIN_SELLER_DETAILS_REQUEST = 'ADMIN_SELLER_DETAILS_REQUEST';
export const ADMIN_SELLER_DETAILS_SUCCESS = 'ADMIN_SELLER_DETAILS_SUCCESS';
export const ADMIN_SELLER_DETAILS_FAIL = 'ADMIN_SELLER_DETAILS_FAIL';
export const ADMIN_SELLER_DETAILS_RESET = 'ADMIN_SELLER_DETAILS_RESET';

export const ADMIN_LOGOUT = 'ADMIN_LOGOUT';
