export const REGISTER_SELLER_USER_REQUEST = 'REGISTER_SELLER_USER_REQUEST';
export const REGISTER_SELLER_USER_SUCCESS = 'REGISTER_SELLER_USER_SUCCESS';
export const REGISTER_SELLER_USER_FAIL = 'REGISTER_SELLER_USER_FAIL';

export const LOGIN_SELLER_USER_REQUEST = 'LOGIN_SELLER_USER_REQUEST';
export const LOGIN_SELLER_USER_SUCCESS = 'LOGIN_SELLER_USER_SUCCESS';
export const LOGIN_SELLER_USER_FAIL = 'LOGIN_SELLER_USER_FAIL';

export const UPDATE_SELLER_USER_REQUEST = 'UPDATE_SELLER_USER_REQUEST';
export const UPDATE_SELLER_USER_SUCCESS = 'UPDATE_SELLER_USER_SUCCESS';
export const UPDATE_SELLER_USER_FAIL = 'UPDATE_SELLER_USER_FAIL';
export const UPDATE_SELLER_USER_RESET = 'UPDATE_SELLER_USER_RESET';

export const ADMIN_LOGOUT = 'ADMIN_LOGOUT';
